Feat/add mobile page
CEBAnder/fake-burrberry-frontend pull request #1
Opened 2017-08-03 18:49 UTC by CEBAnder

2017-08-04 08:20 UTC, evgenyrodionov commented
Коммиты не по формату

2017-08-04 08:27 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28960536-c2387cb0-7907-11e7-885b-ded11e8ccbe0.png)
![image](https://user-images.githubusercontent.com/775692/28960550-cff79d36-7907-11e7-9184-7dd5cd5719c7.png)
![image](https://user-images.githubusercontent.com/775692/28960553-d666cb9c-7907-11e7-9850-fb8e1446e3bb.png)

2017-08-04 19:41 UTC, evgenyrodionov commented
На след проверку

2017-08-04 19:44 UTC, CEBAnder commented
В смысле?

2017-08-05 14:36 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28996231-7e17682c-7a04-11e7-8dad-06b5748d543e.png)

2017-08-05 14:37 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28996238-b41893f6-7a04-11e7-98d5-6f8c7135293a.png)

2017-08-05 14:43 UTC, imevro requested changes

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +    <img class="clothes-image" src='../images/clothes images/first-item/bitmap.png' alt="first-item-image">
почему стиль скачет от одинарных кавычек к двойным

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +    <button class="size-help-button">NEED SIZE HELP?</button>
нейминг плохой: `size-help`, `find-store`, `select-size` как частные случаи кнопки, а не кнопка как частное селект сайза

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +    <button class="size-help-button">NEED SIZE HELP?</button>
плюс кнопки бывают primary, бывают secondary, называй их по назначению, а не по использованию

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +  <div>
зачем этот див?

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +  <div>
кстати очень много дивов, познакомься с section

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +          <p class="item-description">Raglan sleeves and a concealed button closure complement the clean tailored lines.</p>
проблемы в описании

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +      <div class="item-accordeon-pane">
нейминг типа ИТЕМ — плохой

2017-08-05 14:43 UTC, evgenyrodionov commented on pages/mobile-page.html
> +    <div class="we-recommend-string">
зачем тут див

2017-08-05 14:43 UTC, evgenyrodionov commented on styles/style.css
> +.logo-image-div {
а если я захочу сменить тег? почему у тебя в классе отражен тег где он используется?

2017-08-05 14:43 UTC, evgenyrodionov commented on styles/style.css
> +.clothes-basic-info {
а если верстка будет для раздела аксессуаров? че делать? заводить дублирующие классы?

2017-08-05 18:48 UTC, imevro requested changes
даже не стал дальше проверять

2017-08-05 18:48 UTC, evgenyrodionov commented on pages/mobile-page.html
> +  <div>
Соу? чё за игнор?

2017-08-05 18:48 UTC, evgenyrodionov commented on pages/mobile-page.html
> +          <ul class="product-properties-list">
читай телеграф — описания приходят с сервера поэтому у них не будет классов

2017-08-05 18:48 UTC, evgenyrodionov commented on styles/style.css
> +.logo-image-div {
И?

2017-08-05 20:00 UTC, CEBAnder commented on styles/style.css
> +.logo-image-div {
Вопрос про боди? Это сделано, так как в хроме изначально у него есть какие-то марджины.

2017-08-07 12:03 UTC, merged